version: '3'
services:
# ==============================================================================
  web:
    image: verbral/php-c9:7.1-apache
    working_dir: ${PWD}
    environment:
      DOCUMENT_ROOT: ${PWD}/web
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      WAKATIME_API_KEY: ${WAKATIME_API_KEY}
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/home/docker/.ssh
    ports:
      - 8181:8181
      - 81:80
