<?php
/**
 * FullProjectNotify
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VerbruggenAlex\PhpDiffy\Model;

use \ArrayAccess;
use \VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * FullProjectNotify Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FullProjectNotify implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FullProject_notify';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ps_notify_screenshot' => 'bool',
'ps_notify_diff' => 'bool',
'ps_notify_diff_percent' => 'BigDecimal',
'ps_notify_emails' => 'string',
'ps_notify_slack_channel' => 'string',
'ps_notify_slack_webhook_url' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ps_notify_screenshot' => null,
'ps_notify_diff' => null,
'ps_notify_diff_percent' => null,
'ps_notify_emails' => null,
'ps_notify_slack_channel' => null,
'ps_notify_slack_webhook_url' => 'url'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ps_notify_screenshot' => 'psNotifyScreenshot',
'ps_notify_diff' => 'psNotifyDiff',
'ps_notify_diff_percent' => 'psNotifyDiffPercent',
'ps_notify_emails' => 'psNotifyEmails',
'ps_notify_slack_channel' => 'psNotifySlackChannel',
'ps_notify_slack_webhook_url' => 'psNotifySlackWebhookUrl'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ps_notify_screenshot' => 'setPsNotifyScreenshot',
'ps_notify_diff' => 'setPsNotifyDiff',
'ps_notify_diff_percent' => 'setPsNotifyDiffPercent',
'ps_notify_emails' => 'setPsNotifyEmails',
'ps_notify_slack_channel' => 'setPsNotifySlackChannel',
'ps_notify_slack_webhook_url' => 'setPsNotifySlackWebhookUrl'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ps_notify_screenshot' => 'getPsNotifyScreenshot',
'ps_notify_diff' => 'getPsNotifyDiff',
'ps_notify_diff_percent' => 'getPsNotifyDiffPercent',
'ps_notify_emails' => 'getPsNotifyEmails',
'ps_notify_slack_channel' => 'getPsNotifySlackChannel',
'ps_notify_slack_webhook_url' => 'getPsNotifySlackWebhookUrl'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ps_notify_screenshot'] = isset($data['ps_notify_screenshot']) ? $data['ps_notify_screenshot'] : null;
        $this->container['ps_notify_diff'] = isset($data['ps_notify_diff']) ? $data['ps_notify_diff'] : null;
        $this->container['ps_notify_diff_percent'] = isset($data['ps_notify_diff_percent']) ? $data['ps_notify_diff_percent'] : null;
        $this->container['ps_notify_emails'] = isset($data['ps_notify_emails']) ? $data['ps_notify_emails'] : null;
        $this->container['ps_notify_slack_channel'] = isset($data['ps_notify_slack_channel']) ? $data['ps_notify_slack_channel'] : null;
        $this->container['ps_notify_slack_webhook_url'] = isset($data['ps_notify_slack_webhook_url']) ? $data['ps_notify_slack_webhook_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ps_notify_screenshot
     *
     * @return bool
     */
    public function getPsNotifyScreenshot()
    {
        return $this->container['ps_notify_screenshot'];
    }

    /**
     * Sets ps_notify_screenshot
     *
     * @param bool $ps_notify_screenshot ps_notify_screenshot
     *
     * @return $this
     */
    public function setPsNotifyScreenshot($ps_notify_screenshot)
    {
        $this->container['ps_notify_screenshot'] = $ps_notify_screenshot;

        return $this;
    }

    /**
     * Gets ps_notify_diff
     *
     * @return bool
     */
    public function getPsNotifyDiff()
    {
        return $this->container['ps_notify_diff'];
    }

    /**
     * Sets ps_notify_diff
     *
     * @param bool $ps_notify_diff ps_notify_diff
     *
     * @return $this
     */
    public function setPsNotifyDiff($ps_notify_diff)
    {
        $this->container['ps_notify_diff'] = $ps_notify_diff;

        return $this;
    }

    /**
     * Gets ps_notify_diff_percent
     *
     * @return BigDecimal
     */
    public function getPsNotifyDiffPercent()
    {
        return $this->container['ps_notify_diff_percent'];
    }

    /**
     * Sets ps_notify_diff_percent
     *
     * @param BigDecimal $ps_notify_diff_percent ps_notify_diff_percent
     *
     * @return $this
     */
    public function setPsNotifyDiffPercent($ps_notify_diff_percent)
    {
        $this->container['ps_notify_diff_percent'] = $ps_notify_diff_percent;

        return $this;
    }

    /**
     * Gets ps_notify_emails
     *
     * @return string
     */
    public function getPsNotifyEmails()
    {
        return $this->container['ps_notify_emails'];
    }

    /**
     * Sets ps_notify_emails
     *
     * @param string $ps_notify_emails ps_notify_emails
     *
     * @return $this
     */
    public function setPsNotifyEmails($ps_notify_emails)
    {
        $this->container['ps_notify_emails'] = $ps_notify_emails;

        return $this;
    }

    /**
     * Gets ps_notify_slack_channel
     *
     * @return string
     */
    public function getPsNotifySlackChannel()
    {
        return $this->container['ps_notify_slack_channel'];
    }

    /**
     * Sets ps_notify_slack_channel
     *
     * @param string $ps_notify_slack_channel ps_notify_slack_channel
     *
     * @return $this
     */
    public function setPsNotifySlackChannel($ps_notify_slack_channel)
    {
        $this->container['ps_notify_slack_channel'] = $ps_notify_slack_channel;

        return $this;
    }

    /**
     * Gets ps_notify_slack_webhook_url
     *
     * @return string
     */
    public function getPsNotifySlackWebhookUrl()
    {
        return $this->container['ps_notify_slack_webhook_url'];
    }

    /**
     * Sets ps_notify_slack_webhook_url
     *
     * @param string $ps_notify_slack_webhook_url ps_notify_slack_webhook_url
     *
     * @return $this
     */
    public function setPsNotifySlackWebhookUrl($ps_notify_slack_webhook_url)
    {
        $this->container['ps_notify_slack_webhook_url'] = $ps_notify_slack_webhook_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
