<?php
/**
 * FullProjectModify
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VerbruggenAlex\PhpDiffy\Model;

use \ArrayAccess;
use \VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * FullProjectModify Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FullProjectModify implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FullProject_modify';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ps_screenshot_crop' => 'string',
'ps_screenshot_cut' => 'string',
'ps_screenshot_exclude' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ps_screenshot_crop' => null,
'ps_screenshot_cut' => null,
'ps_screenshot_exclude' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ps_screenshot_crop' => 'psScreenshotCrop',
'ps_screenshot_cut' => 'psScreenshotCut',
'ps_screenshot_exclude' => 'psScreenshotExclude'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ps_screenshot_crop' => 'setPsScreenshotCrop',
'ps_screenshot_cut' => 'setPsScreenshotCut',
'ps_screenshot_exclude' => 'setPsScreenshotExclude'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ps_screenshot_crop' => 'getPsScreenshotCrop',
'ps_screenshot_cut' => 'getPsScreenshotCut',
'ps_screenshot_exclude' => 'getPsScreenshotExclude'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ps_screenshot_crop'] = isset($data['ps_screenshot_crop']) ? $data['ps_screenshot_crop'] : null;
        $this->container['ps_screenshot_cut'] = isset($data['ps_screenshot_cut']) ? $data['ps_screenshot_cut'] : null;
        $this->container['ps_screenshot_exclude'] = isset($data['ps_screenshot_exclude']) ? $data['ps_screenshot_exclude'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ps_screenshot_crop
     *
     * @return string
     */
    public function getPsScreenshotCrop()
    {
        return $this->container['ps_screenshot_crop'];
    }

    /**
     * Sets ps_screenshot_crop
     *
     * @param string $ps_screenshot_crop ps_screenshot_crop
     *
     * @return $this
     */
    public function setPsScreenshotCrop($ps_screenshot_crop)
    {
        $this->container['ps_screenshot_crop'] = $ps_screenshot_crop;

        return $this;
    }

    /**
     * Gets ps_screenshot_cut
     *
     * @return string
     */
    public function getPsScreenshotCut()
    {
        return $this->container['ps_screenshot_cut'];
    }

    /**
     * Sets ps_screenshot_cut
     *
     * @param string $ps_screenshot_cut ps_screenshot_cut
     *
     * @return $this
     */
    public function setPsScreenshotCut($ps_screenshot_cut)
    {
        $this->container['ps_screenshot_cut'] = $ps_screenshot_cut;

        return $this;
    }

    /**
     * Gets ps_screenshot_exclude
     *
     * @return string
     */
    public function getPsScreenshotExclude()
    {
        return $this->container['ps_screenshot_exclude'];
    }

    /**
     * Sets ps_screenshot_exclude
     *
     * @param string $ps_screenshot_exclude ps_screenshot_exclude
     *
     * @return $this
     */
    public function setPsScreenshotExclude($ps_screenshot_exclude)
    {
        $this->container['ps_screenshot_exclude'] = $ps_screenshot_exclude;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
