<?php
/**
 * CompareCustomEnvironmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * CompareCustomEnvironmentTest Class Doc Comment
 *
 * @category    Class
 * @description CompareCustomEnvironment
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompareCustomEnvironmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompareCustomEnvironment"
     */
    public function testCompareCustomEnvironment()
    {
    }

    /**
     * Test attribute "environments"
     */
    public function testPropertyEnvironments()
    {
    }

    /**
     * Test attribute "url1"
     */
    public function testPropertyUrl1()
    {
    }

    /**
     * Test attribute "url2"
     */
    public function testPropertyUrl2()
    {
    }

    /**
     * Test attribute "login1"
     */
    public function testPropertyLogin1()
    {
    }

    /**
     * Test attribute "login2"
     */
    public function testPropertyLogin2()
    {
    }
}
