<?php
/**
 * FullProjectNotifyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * FullProjectNotifyTest Class Doc Comment
 *
 * @category    Class
 * @description FullProjectNotify
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullProjectNotifyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullProjectNotify"
     */
    public function testFullProjectNotify()
    {
    }

    /**
     * Test attribute "ps_notify_screenshot"
     */
    public function testPropertyPsNotifyScreenshot()
    {
    }

    /**
     * Test attribute "ps_notify_diff"
     */
    public function testPropertyPsNotifyDiff()
    {
    }

    /**
     * Test attribute "ps_notify_diff_percent"
     */
    public function testPropertyPsNotifyDiffPercent()
    {
    }

    /**
     * Test attribute "ps_notify_emails"
     */
    public function testPropertyPsNotifyEmails()
    {
    }

    /**
     * Test attribute "ps_notify_slack_channel"
     */
    public function testPropertyPsNotifySlackChannel()
    {
    }

    /**
     * Test attribute "ps_notify_slack_webhook_url"
     */
    public function testPropertyPsNotifySlackWebhookUrl()
    {
    }
}
