<?php
/**
 * FullDiffTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * FullDiffTest Class Doc Comment
 *
 * @category    Class
 * @description FullDiff
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullDiffTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullDiff"
     */
    public function testFullDiff()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "snapshot1"
     */
    public function testPropertySnapshot1()
    {
    }

    /**
     * Test attribute "snapshot2"
     */
    public function testPropertySnapshot2()
    {
    }

    /**
     * Test attribute "diffs"
     */
    public function testPropertyDiffs()
    {
    }

    /**
     * Test attribute "env1"
     */
    public function testPropertyEnv1()
    {
    }

    /**
     * Test attribute "env2"
     */
    public function testPropertyEnv2()
    {
    }

    /**
     * Test attribute "env1_url"
     */
    public function testPropertyEnv1Url()
    {
    }

    /**
     * Test attribute "env2_url"
     */
    public function testPropertyEnv2Url()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "archive_url"
     */
    public function testPropertyArchiveUrl()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }
}
