<?php
/**
 * FullProjectAuthenticateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * FullProjectAuthenticateTest Class Doc Comment
 *
 * @category    Class
 * @description FullProjectAuthenticate
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullProjectAuthenticateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullProjectAuthenticate"
     */
    public function testFullProjectAuthenticate()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "click_element"
     */
    public function testPropertyClickElement()
    {
    }

    /**
     * Test attribute "click_element_selector"
     */
    public function testPropertyClickElementSelector()
    {
    }

    /**
     * Test attribute "login_url"
     */
    public function testPropertyLoginUrl()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "username_selector"
     */
    public function testPropertyUsernameSelector()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "password_selector"
     */
    public function testPropertyPasswordSelector()
    {
    }

    /**
     * Test attribute "submit_selector"
     */
    public function testPropertySubmitSelector()
    {
    }

    /**
     * Test attribute "afterlogin_selector"
     */
    public function testPropertyAfterloginSelector()
    {
    }
}
