<?php
/**
 * FullProjectAdvancedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * FullProjectAdvancedTest Class Doc Comment
 *
 * @category    Class
 * @description FullProjectAdvanced
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullProjectAdvancedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullProjectAdvanced"
     */
    public function testFullProjectAdvanced()
    {
    }

    /**
     * Test attribute "ps_screenshot_bot"
     */
    public function testPropertyPsScreenshotBot()
    {
    }

    /**
     * Test attribute "ps_screenshot_bot_string"
     */
    public function testPropertyPsScreenshotBotString()
    {
    }

    /**
     * Test attribute "ps_screenshot_cookies"
     */
    public function testPropertyPsScreenshotCookies()
    {
    }

    /**
     * Test attribute "ps_screenshot_cookies_string"
     */
    public function testPropertyPsScreenshotCookiesString()
    {
    }

    /**
     * Test attribute "ps_screenshot_delay"
     */
    public function testPropertyPsScreenshotDelay()
    {
    }

    /**
     * Test attribute "ps_screenshot_delay_sec"
     */
    public function testPropertyPsScreenshotDelaySec()
    {
    }

    /**
     * Test attribute "ps_screenshot_no_amin"
     */
    public function testPropertyPsScreenshotNoAmin()
    {
    }

    /**
     * Test attribute "ps_screenshot_proxy"
     */
    public function testPropertyPsScreenshotProxy()
    {
    }

    /**
     * Test attribute "ps_screenshot_proxy_host"
     */
    public function testPropertyPsScreenshotProxyHost()
    {
    }

    /**
     * Test attribute "ps_screenshot_proxy_login"
     */
    public function testPropertyPsScreenshotProxyLogin()
    {
    }

    /**
     * Test attribute "ps_screenshot_proxy_password"
     */
    public function testPropertyPsScreenshotProxyPassword()
    {
    }

    /**
     * Test attribute "ps_screenshot_proxy_port"
     */
    public function testPropertyPsScreenshotProxyPort()
    {
    }

    /**
     * Test attribute "ps_screenshot_scroll"
     */
    public function testPropertyPsScreenshotScroll()
    {
    }
}
