<?php
/**
 * FullProjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * FullProjectTest Class Doc Comment
 *
 * @category    Class
 * @description FullProject
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullProjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullProject"
     */
    public function testFullProject()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }

    /**
     * Test attribute "production"
     */
    public function testPropertyProduction()
    {
    }

    /**
     * Test attribute "staging"
     */
    public function testPropertyStaging()
    {
    }

    /**
     * Test attribute "development"
     */
    public function testPropertyDevelopment()
    {
    }

    /**
     * Test attribute "breakpoints"
     */
    public function testPropertyBreakpoints()
    {
    }

    /**
     * Test attribute "schedule"
     */
    public function testPropertySchedule()
    {
    }

    /**
     * Test attribute "authenticate"
     */
    public function testPropertyAuthenticate()
    {
    }

    /**
     * Test attribute "advanced"
     */
    public function testPropertyAdvanced()
    {
    }

    /**
     * Test attribute "modify"
     */
    public function testPropertyModify()
    {
    }

    /**
     * Test attribute "github_url"
     */
    public function testPropertyGithubUrl()
    {
    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {
    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {
    }
}
