<?php
/**
 * ScreenshotsListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VerbruggenAlex\PhpDiffy;

/**
 * ScreenshotsListTest Class Doc Comment
 *
 * @category    Class
 * @description ScreenshotsList
 * @package     VerbruggenAlex\PhpDiffy
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreenshotsListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScreenshotsList"
     */
    public function testScreenshotsList()
    {
    }

    /**
     * Test attribute "project_name"
     */
    public function testPropertyProjectName()
    {
    }

    /**
     * Test attribute "production"
     */
    public function testPropertyProduction()
    {
    }

    /**
     * Test attribute "staging"
     */
    public function testPropertyStaging()
    {
    }

    /**
     * Test attribute "development"
     */
    public function testPropertyDevelopment()
    {
    }

    /**
     * Test attribute "has_baseline"
     */
    public function testPropertyHasBaseline()
    {
    }

    /**
     * Test attribute "screenshots"
     */
    public function testPropertyScreenshots()
    {
    }

    /**
     * Test attribute "number_items_on_page"
     */
    public function testPropertyNumberItemsOnPage()
    {
    }

    /**
     * Test attribute "total_pages"
     */
    public function testPropertyTotalPages()
    {
    }
}
