<?php
/**
 * DiffsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VerbruggenAlex\PhpDiffy;

use VerbruggenAlex\PhpDiffy\Configuration;
use VerbruggenAlex\PhpDiffy\ApiException;
use VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * DiffsApiTest Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DiffsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for diffsIdActionPut
     *
     * Start/stop diff's jobs.
     *
     */
    public function testDiffsIdActionPut()
    {
    }

    /**
     * Test case for diffsIdDelete
     *
     * Delete Diff.
     *
     */
    public function testDiffsIdDelete()
    {
    }

    /**
     * Test case for diffsIdGet
     *
     * Full info of the Diff.
     *
     */
    public function testDiffsIdGet()
    {
    }

    /**
     * Test case for diffsIdPut
     *
     * Update diff name.
     *
     */
    public function testDiffsIdPut()
    {
    }

    /**
     * Test case for projectsIdDiffsPost
     *
     * Create Diff.
     *
     */
    public function testProjectsIdDiffsPost()
    {
    }
}
