<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VerbruggenAlex\PhpDiffy;

use VerbruggenAlex\PhpDiffy\Configuration;
use VerbruggenAlex\PhpDiffy\ApiException;
use VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for projectsGet
     *
     * List Projects.
     *
     */
    public function testProjectsGet()
    {
    }

    /**
     * Test case for projectsIdComparePost
     *
     * Compare environments.
     *
     */
    public function testProjectsIdComparePost()
    {
    }

    /**
     * Test case for projectsIdDelete
     *
     * Delete Project.
     *
     */
    public function testProjectsIdDelete()
    {
    }

    /**
     * Test case for projectsIdDiffsGet
     *
     * List of Diffs.
     *
     */
    public function testProjectsIdDiffsGet()
    {
    }

    /**
     * Test case for projectsIdGet
     *
     * Get Project information.
     *
     */
    public function testProjectsIdGet()
    {
    }

    /**
     * Test case for projectsIdPost
     *
     * Update Project.
     *
     */
    public function testProjectsIdPost()
    {
    }

    /**
     * Test case for projectsIdScreenshotsGet
     *
     * List of Screenshots.
     *
     */
    public function testProjectsIdScreenshotsGet()
    {
    }

    /**
     * Test case for projectsIdSetBaseLineImageScreenshotIdPut
     *
     * Set as baseline image.
     *
     */
    public function testProjectsIdSetBaseLineImageScreenshotIdPut()
    {
    }

    /**
     * Test case for projectsIdSetBaseLineSetScreenshotIdPut
     *
     * Set whole set as baseline images.
     *
     */
    public function testProjectsIdSetBaseLineSetScreenshotIdPut()
    {
    }

    /**
     * Test case for projectsPost
     *
     * Create Project.
     *
     */
    public function testProjectsPost()
    {
    }

    /**
     * Test case for projectsProjectIdComparePost
     *
     * Compare custom environments.
     *
     */
    public function testProjectsProjectIdComparePost()
    {
    }
}
