<?php
/**
 * ScreenshotsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VerbruggenAlex\PhpDiffy;

use VerbruggenAlex\PhpDiffy\Configuration;
use VerbruggenAlex\PhpDiffy\ApiException;
use VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * ScreenshotsApiTest Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScreenshotsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for projectsIdScreenshotsPost
     *
     * Create Screenshot.
     *
     */
    public function testProjectsIdScreenshotsPost()
    {
    }

    /**
     * Test case for snapshotsIdActionPut
     *
     * Start/stop screenshot's jobs.
     *
     */
    public function testSnapshotsIdActionPut()
    {
    }

    /**
     * Test case for snapshotsIdDelete
     *
     * Delete Screenshot.
     *
     */
    public function testSnapshotsIdDelete()
    {
    }

    /**
     * Test case for snapshotsIdGet
     *
     * Full info of the Screenshot.
     *
     */
    public function testSnapshotsIdGet()
    {
    }

    /**
     * Test case for snapshotsIdPut
     *
     * Update screenshot name.
     *
     */
    public function testSnapshotsIdPut()
    {
    }
}
