<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VerbruggenAlex\PhpDiffy;

use VerbruggenAlex\PhpDiffy\Configuration;
use VerbruggenAlex\PhpDiffy\ApiException;
use VerbruggenAlex\PhpDiffy\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  VerbruggenAlex\PhpDiffy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for authKeyPost
     *
     * Login user via Key.
     *
     */
    public function testAuthKeyPost()
    {
    }

    /**
     * Test case for loginCheckPost
     *
     * Login user.
     *
     */
    public function testLoginCheckPost()
    {
    }

    /**
     * Test case for resetPasswordEmailPost
     *
     * Reset user's password.
     *
     */
    public function testResetPasswordEmailPost()
    {
    }

    /**
     * Test case for userKeysGet
     *
     * Get API keys of the current user.
     *
     */
    public function testUserKeysGet()
    {
    }

    /**
     * Test case for userKeysKeyDelete
     *
     * Delete user's API key.
     *
     */
    public function testUserKeysKeyDelete()
    {
    }

    /**
     * Test case for userKeysPost
     *
     * Add new key.
     *
     */
    public function testUserKeysPost()
    {
    }

    /**
     * Test case for usersChangePasswordPost
     *
     * Change user's password.
     *
     */
    public function testUsersChangePasswordPost()
    {
    }
}
